### ISSUE TITLE
haproxy download failure

### ISSUE THREAD

**Issue by ipolyzos** [starkandwayne/concourse-deployment#8]
Running a concourse deployment a run into failure due to inability to download haproxy version.

Here is the log from deploy operation:
```
Using remote release 'https://github.com/cloudfoundry-community/haproxy-boshrelease/releases/download/v8.0.9/haproxy-8.0.9.tgz'

Director task 31
  Started downloading remote release > Downloading remote release. Failed: Downloading remote release failed. Check task debug log for details. (00:00:01)

Error 100001: Downloading remote release failed. Check task debug log for details.

Task 31 error
```

 And below I have the output of bosk task --debug:

```
I, [2017-04-25 13:44:27 #14362] []  INFO -- DirectorJobRunner: Starting task: 30
I, [2017-04-25 13:44:27 #14362] [task:30]  INFO -- DirectorJobRunner: Creating job
D, [2017-04-25 13:44:27 #14362] [task:30] DEBUG -- DirectorJobRunner: (0.000125s) SELECT NULL
D, [2017-04-25 13:44:27 #14362] [task:30] DEBUG -- DirectorJobRunner: (0.000191s) SELECT * FROM "tasks" WHERE "id" = 30
D, [2017-04-25 13:44:27 #14362] [task:30] DEBUG -- DirectorJobRunner: (0.000123s) SELECT NULL
D, [2017-04-25 13:44:27 #14362] [task:30] DEBUG -- DirectorJobRunner: (0.000186s) SELECT * FROM "tasks" WHERE "id" = 30
I, [2017-04-25 13:44:27 #14362] [task:30]  INFO -- DirectorJobRunner: Performing task: #<Bosh::Director::Models::Task @values={:id=>30, :state=>"queued", :timestamp=>2017-04-25 13:44:26 UTC, :description=>"create release", :result=>nil, :output=>"/var/vcap/store/director/tasks/30", :checkpoint_time=>2017-04-25 13:44:26 UTC, :type=>"update_release", :username=>"admin", :deployment_name=>nil, :started_at=>nil}>
D, [2017-04-25 13:44:27 #14362] [task:30] DEBUG -- DirectorJobRunner: (0.000135s) SELECT NULL
D, [2017-04-25 13:44:27 #14362] [task:30] DEBUG -- DirectorJobRunner: (0.000075s) BEGIN
D, [2017-04-25 13:44:27 #14362] [task:30] DEBUG -- DirectorJobRunner: (0.000400s) UPDATE "tasks" SET "state" = 'processing', "timestamp" = '2017-04-25 13:44:27.927250+0000', "description" = 'create release', "result" = NULL, "output" = '/var/vcap/store/director/tasks/30', "checkpoint_time" = '2017-04-25 13:44:27.927386+0000', "type" = 'update_release', "username" = 'admin', "deployment_name" = NULL, "started_at" = '2017-04-25 13:44:27.927326+0000' WHERE ("id" = 30)
D, [2017-04-25 13:44:27 #14362] [task:30] DEBUG -- DirectorJobRunner: (0.000946s) COMMIT
I, [2017-04-25 13:44:27 #14362] [task:30]  INFO -- DirectorJobRunner: Processing update release
I, [2017-04-25 13:44:27 #14362] [task:30]  INFO -- DirectorJobRunner: Downloading remote release
I, [2017-04-25 13:44:27 #14362] [task:30]  INFO -- DirectorJobRunner: Downloading remote release from https://github.com/cloudfoundry-community/haproxy-boshrelease/releases/download/v8.0.9/haproxy-8.0.9.tgz
E, [2017-04-25 13:44:28 #14362] [task:30] ERROR -- DirectorJobRunner: Downloading remote release from https://github.com/cloudfoundry-community/haproxy-boshrelease/releases/download/v8.0.9/haproxy-8.0.9.tgz failed: Moved Permanently
E, [2017-04-25 13:44:28 #14362] [task:30] ERROR -- DirectorJobRunner: Downloading remote release failed. Check task debug log for details.
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/download_helper.rb:42:in `block (2 levels) in download_remote_file'
/var/vcap/packages/ruby/lib/ruby/2.3.0/net/http.rb:1446:in `block in transport_request'
/var/vcap/packages/ruby/lib/ruby/2.3.0/net/http/response.rb:163:in `reading_body'
/var/vcap/packages/ruby/lib/ruby/2.3.0/net/http.rb:1445:in `transport_request'
/var/vcap/packages/ruby/lib/ruby/2.3.0/net/http.rb:1407:in `request'
/var/vcap/packages/ruby/lib/ruby/2.3.0/net/http.rb:1308:in `request_get'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/download_helper.rb:19:in `block in download_remote_file'
/var/vcap/packages/ruby/lib/ruby/2.3.0/net/http.rb:853:in `start'
/var/vcap/packages/ruby/lib/ruby/2.3.0/net/http.rb:584:in `start'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/download_helper.rb:16:in `download_remote_file'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/update_release.rb:67:in `download_remote_release'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/update_release.rb:45:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/base_job.rb:62:in `block in single_step_stage'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/base_job.rb:56:in `block in track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/base_job.rb:54:in `track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/base_job.rb:62:in `single_step_stage'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/update_release.rb:45:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/job_runner.rb:106:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/job_runner.rb:32:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/job_runner.rb:32:in `run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/db_job.rb:32:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/db_job.rb:80:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:1046:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2017-04-25 13:44:28 #14362] [task:30] DEBUG -- DirectorJobRunner: (0.000195s) SELECT NULL
D, [2017-04-25 13:44:28 #14362] [task:30] DEBUG -- DirectorJobRunner: (0.000076s) BEGIN
D, [2017-04-25 13:44:28 #14362] [task:30] DEBUG -- DirectorJobRunner: (0.000296s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2017-04-25 13:44:28.319331+0000', "description" = 'create release', "result" = 'Downloading remote release failed. Check task debug log for details.', "output" = '/var/vcap/store/director/tasks/30', "checkpoint_time" = '2017-04-25 13:44:27.927386+0000', "type" = 'update_release', "username" = 'admin', "deployment_name" = NULL, "started_at" = '2017-04-25 13:44:27.927326+0000' WHERE ("id" = 30)
D, [2017-04-25 13:44:28 #14362] [task:30] DEBUG -- DirectorJobRunner: (0.000904s) COMMIT
I, [2017-04-25 13:44:28 #14362] []  INFO -- DirectorJobRunner: Task took 0.397069564 seconds to process.
```
Hower when manually try to download for the link i.e. https://github.com/cloudfoundry-community/haproxy-boshrelease/releases/download/v8.0.9/haproxy-8.0.9.tgz it works. Could you please advice?

**Comment by geofffranks** [comment]
This likely has to do with haproxy moving from cloudfoundry-community to cloudfoundry-incubator.

**Comment by ipolyzos** [comment]
I can confirm it works and proceeds with the download when upgrade version to 8.1.0.

p.s a pull request submited...

**Comment by alexanelli** [comment]
@ipolyzos Hey I just want to confirm that I'm closing this issue as Geoff had successfully merged your pull request on Apr 25th

**Comment by ipolyzos** [comment]
@xanderrman  I can confirm it is fine. Please proceed. Thank you.
